### ISSUE TITLE
Java Script Beautification is not happening in Ace Editor

### ISSUE THREAD

**Issue by PradeepPsudo** [ajaxorg/ace-builds#119]
Hi,

JavaScript code beautification is not happening properly in Ace Editor, if i have a code with if and else if condition it is removing space between "else if" condition and making it as "elseif" which is a Syntax error.

I checked in the Ace Editor Demo link and it is reproducible.  Please find  below link for the same. https://ace.c9.io/build/kitchen-sink.html.

Kindly look into this issue.

Regards,
Pradeep

**Comment by nightwing** [comment]
Ace doesn't support code beautification, what command do you use?

**Comment by PradeepPsudo** [comment]
Command : ctrl + shift + b.
I am using ext-beautify.js file, it supports beautification of other languages like CSS,LESS,SCSS etc.

**Comment by Sophist-UK** [comment]
Well - using the default CSS document in the kitchen-sink beautification is actually uglification.

However, looking inside the ext/beautify.js file I see that it says:
```
var TokenIterator = require("ace/token_iterator").TokenIterator;
var phpTransform = require("./beautify/php_rules").transform;
```
which suggests to me that this is only for php code.

And this will, of course, explain `else if` becoming `elseif` because this is a reasonable improvement in php code.

But if @PradeepPsudo  would like to extend it to handle CSS, JS, etc. I think we would all be grateful.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3589 have greatly improved the beautify extension
